NetabareBlock:
  api:
    admin-twitter-id: 
    consumer-key: 
    consumer-secret: 
    domain: http://localhost:8080
spring:
  datasource:
    url:  jdbc:postgresql://localhost/netabareblock
    username: 
    password: 
    driverClassName: org.postgresql.Driver